const studentData = [
  {
    id: 1,
    firstName: 'Rip',
    lastName: 'Dobbings',
    email: 'rdobbings0@google.es',
    mobileNumber: 'Male',
  },
  {
    id: 2,
    firstName: 'Fidela',
    lastName: 'Laville',
    email: 'flaville1@utexas.edu',
    mobileNumber: 'Female',
  },
  {
    id: 3,
    firstName: 'Terrence',
    lastName: 'Pinckney',
    email: 'tpinckney2@un.org',
    mobileNumber: 'Male',
  },
  {
    id: 4,
    firstName: 'Tamqrah',
    lastName: 'Aikin',
    email: 'taikin3@hostgator.com',
    mobileNumber: 'Female',
  },
  {
    id: 5,
    firstName: 'Rachelle',
    lastName: 'Collingridge',
    email: 'rcollingridge4@usda.gov',
    mobileNumber: 'Female',
  },
  {
    id: 6,
    firstName: 'Colver',
    lastName: 'Erdes',
    email: 'cerdes5@deliciousdays.com',
    mobileNumber: 'Male',
  },
  {
    id: 7,
    firstName: 'Maryann',
    lastName: 'Milkeham',
    email: 'mmilkeham6@who.int',
    mobileNumber: 'Female',
  },
  {
    id: 8,
    firstName: 'Frasier',
    lastName: 'Werrit',
    email: 'fwerrit7@omniture.com',
    mobileNumber: 'Male',
  },
  {
    id: 9,
    firstName: 'Arv',
    lastName: 'Elies',
    email: 'aelies8@usgs.gov',
    mobileNumber: 'Male',
  },
  {
    id: 10,
    firstName: 'Anabal',
    lastName: 'Christophe',
    email: 'achristophe9@mac.com',
    mobileNumber: 'Female',
  },
  {
    id: 11,
    firstName: 'Flory',
    lastName: 'Gave',
    email: 'fgavea@buzzfeed.com',
    mobileNumber: 'Female',
  },
  {
    id: 12,
    firstName: 'Julienne',
    lastName: 'Stroban',
    email: 'jstrobanb@google.es',
    mobileNumber: 'Female',
  },
  {
    id: 13,
    firstName: 'Terza',
    lastName: 'Codeman',
    email: 'tcodemanc@hostgator.com',
    mobileNumber: 'Female',
  },
  {
    id: 14,
    firstName: 'Seana',
    lastName: 'Eskriett',
    email: 'seskriettd@chicagotribune.com',
    mobileNumber: 'Female',
  },
  {
    id: 15,
    firstName: 'Edith',
    lastName: 'Shawell',
    email: 'eshawelle@slate.com',
    mobileNumber: 'Female',
  },
  {
    id: 16,
    firstName: 'Beitris',
    lastName: 'Le - Count',
    email: 'blecountf@archive.org',
    mobileNumber: 'Genderqueer',
  },
  {
    id: 17,
    firstName: 'Bettina',
    lastName: 'Farey',
    email: 'bfareyg@github.io',
    mobileNumber: 'Female',
  },
  {
    id: 18,
    firstName: 'Georgianna',
    lastName: 'Beade',
    email: 'gbeadeh@illinois.edu',
    mobileNumber: 'Female',
  },
  {
    id: 19,
    firstName: 'Kamilah',
    lastName: 'Tames',
    email: 'ktamesi@smugmug.com',
    mobileNumber: 'Female',
  },
  {
    id: 20,
    firstName: 'Findlay',
    lastName: 'Riddick',
    email: 'friddickj@statcounter.com',
    mobileNumber: 'Male',
  },
  {
    id: 21,
    firstName: 'Troy',
    lastName: 'Rudgerd',
    email: 'trudgerdk@example.com',
    mobileNumber: 'Male',
  },
  {
    id: 22,
    firstName: 'Daffy',
    lastName: 'Silman',
    email: 'dsilmanl@wufoo.com',
    mobileNumber: 'Female',
  },
  {
    id: 23,
    firstName: 'Helene',
    lastName: 'Ianson',
    email: 'hiansonm@google.cn',
    mobileNumber: 'Female',
  },
  {
    id: 24,
    firstName: 'Cary',
    lastName: 'Canfer',
    email: 'ccanfern@hp.com',
    mobileNumber: 'Male',
  },
  {
    id: 25,
    firstName: 'Thalia',
    lastName: 'Oxbie',
    email: 'toxbieo@tiny.cc',
    mobileNumber: 'Female',
  },
];

export default studentData;
