import { faker } from '@faker-js/faker';
import { sample } from 'lodash';

// ----------------------------------------------------------------------

const users = [
  {
    id: 1,
    firstName: 'Abbey',
    lastName: 'Kellick',
    email: 'akellick0@china.com.cn',
    mobileNumber: '2',
  },
  {
    id: 2,
    firstName: 'Ursala',
    lastName: 'Lillie',
    email: 'ulillie1@utexas.edu',
    mobileNumber: '8',
  },
  {
    id: 3,
    firstName: 'Laural',
    lastName: 'Armour',
    email: 'larmour2@nbcnews.com',
    mobileNumber: '2',
  },
  {
    id: 4,
    firstName: 'Philippa',
    lastName: 'Espinazo',
    email: 'pespinazo3@apache.org',
    mobileNumber: '3',
  },
  {
    id: 5,
    firstName: 'Samaria',
    lastName: 'Claeskens',
    email: 'sclaeskens4@barnesandnoble.com',
    mobileNumber: '8',
  },
  {
    id: 6,
    firstName: 'Shaun',
    lastName: 'Kaspar',
    email: 'skaspar5@skype.com',
    mobileNumber: '9',
  },
  {
    id: 7,
    firstName: 'Riobard',
    lastName: 'Edgworth',
    email: 'redgworth6@friendfeed.com',
    mobileNumber: '2',
  },
  {
    id: 8,
    firstName: 'Jaime',
    lastName: 'Zanetto',
    email: 'jzanetto7@angelfire.com',
    mobileNumber: '2',
  },
  {
    id: 9,
    firstName: 'Umeko',
    lastName: 'Sickert',
    email: 'usickert8@army.mil',
    mobileNumber: '10',
  },
  {
    id: 10,
    firstName: 'Yul',
    lastName: 'Siney',
    email: 'ysiney9@webnode.com',
    mobileNumber: '2',
  },
  {
    id: 11,
    firstName: 'Harmon',
    lastName: 'Alloway',
    email: 'hallowaya@soundcloud.com',
    mobileNumber: '7',
  },
  {
    id: 12,
    firstName: 'Napoleon',
    lastName: 'Cakebread',
    email: 'ncakebreadb@alibaba.com',
    mobileNumber: '8',
  },
  {
    id: 13,
    firstName: 'Jessey',
    lastName: 'Caudray',
    email: 'jcaudrayc@github.com',
    mobileNumber: '3',
  },
  {
    id: 14,
    firstName: 'Filia',
    lastName: 'McGougan',
    email: 'fmcgougand@addthis.com',
    mobileNumber: '7',
  },
  {
    id: 15,
    firstName: 'Maximo',
    lastName: 'Bassett',
    email: 'mbassette@imageshack.us',
    mobileNumber: '1',
  },
  {
    id: 16,
    firstName: 'Sal',
    lastName: 'Kainz',
    email: 'skainzf@apache.org',
    mobileNumber: '1',
  },
  {
    id: 17,
    firstName: 'Christiano',
    lastName: 'Woolstenholmes',
    email: 'cwoolstenholmesg@accuweather.com',
    mobileNumber: '1',
  },
  {
    id: 18,
    firstName: 'Lyndsay',
    lastName: 'Rowswell',
    email: 'lrowswellh@sbwire.com',
    mobileNumber: '9',
  },
  {
    id: 19,
    firstName: 'Jayne',
    lastName: 'Bickers',
    email: 'jbickersi@spotify.com',
    mobileNumber: '5',
  },
  {
    id: 20,
    firstName: 'Ailsun',
    lastName: 'Kingh',
    email: 'akinghj@bluehost.com',
    mobileNumber: '2',
  },
  {
    id: 21,
    firstName: 'Joan',
    lastName: 'Orrell',
    email: 'jorrellk@moonfruit.com',
    mobileNumber: '6',
  },
  {
    id: 22,
    firstName: 'Nicholas',
    lastName: 'Koenen',
    email: 'nkoenenl@sina.com.cn',
    mobileNumber: '1',
  },
  {
    id: 23,
    firstName: 'Vinson',
    lastName: 'Sedwick',
    email: 'vsedwickm@nytimes.com',
    mobileNumber: '5',
  },
  {
    id: 24,
    firstName: 'Zorine',
    lastName: 'Beeton',
    email: 'zbeetonn@myspace.com',
    mobileNumber: '10',
  },
  {
    id: 25,
    firstName: 'Lammond',
    lastName: 'Searles',
    email: 'lsearleso@ted.com',
    mobileNumber: '4',
  },
  {
    id: 26,
    firstName: 'Dare',
    lastName: 'Canero',
    email: 'dcanerop@cyberchimps.com',
    mobileNumber: '3',
  },
  {
    id: 27,
    firstName: 'Colly',
    lastName: 'Leary',
    email: 'clearyq@hatena.ne.jp',
    mobileNumber: '6',
  },
  {
    id: 28,
    firstName: 'Philippine',
    lastName: 'Kubala',
    email: 'pkubalar@webmd.com',
    mobileNumber: '9',
  },
  {
    id: 29,
    firstName: 'Benjie',
    lastName: 'Bridgett',
    email: 'bbridgetts@globo.com',
    mobileNumber: '3',
  },
  {
    id: 30,
    firstName: 'Atlante',
    lastName: 'Farmloe',
    email: 'afarmloet@wp.com',
    mobileNumber: '8',
  },
];

// [...Array(24)].map((_, index) => ({
//   id: faker.datatype.uuid(),
//   avatarUrl: `/assets/images/avatars/avatar_${index + 1}.jpg`,
//   FirstName: faker.name.fullName(),
//   LastName: faker.company.name(),
//   Email: faker.internet.email(),
//   status: sample(['active', 'banned']),
//   role: sample([
//     'Leader',
//     'Hr Manager',
//     'UI Designer',
//     'UX Designer',
//     'UI/UX Designer',
//     'Project Manager',
//     'Backend Developer',
//     'Full Stack Designer',
//     'Front End Developer',
//     'Full Stack Developer',
//   ]),
// }));

export default users;
